version: '3'

services:
  ticket-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 15432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=ticketing_system

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for local development
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Set JVM heap size
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false


volumes:
  esdata:


